version: "3.9"

services:

  news-service:
    build: ./news_service
    container_name: news-service
    ports:
      - "8001:8000"

  auth-service:
    build: ./auth_service
    container_name: auth-service
    ports:
      - "8002:8000"

  analytics-service:
    build: ./analytics_service
    container_name: analytics-service
    ports:
      - "8003:8000"
    depends_on:
      - news-service
